<a href="https://colab.research.google.com/github/tilly963963/pytorch/blob/main/Chapter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
'''
向量 矩陣 張量
'''

'\n向量 矩陣 張量\n'

In [ ]:
z = torch.Tensor(4,5) #2的維度 各維度的size
z

tensor([[-1.3073e-20,  3.0925e-41,  7.0065e-44,  6.8664e-44,  6.3058e-44],
        [ 6.7262e-44,  7.1466e-44,  6.3058e-44,  6.7262e-44,  7.5670e-44],
        [ 1.1771e-43,  6.8664e-44,  7.1466e-44,  8.1275e-44,  7.2868e-44],
        [ 6.8664e-44,  8.1275e-44,  6.8664e-44,  7.2868e-44,  6.4460e-44]])

In [ ]:
z.dtype

torch.float32

In [ ]:
a = torch.FloatTensor(4,5)
b = torch.FloatTensor([[2,3],[4,5]])
a

tensor([[-1.3076e-20,  3.0925e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  3.5733e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  3.5733e-43,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [ ]:
b

tensor([[2., 3.],
        [4., 5.]])

In [ ]:
a.dtype

torch.float32

In [ ]:
b.dtype

torch.float32

In [ ]:
a = torch.IntTensor(4,5)
b = torch.IntTensor([[2,3],[4,5]])
a

tensor([[-1636373120,       22069,          50,          49,          45],
        [         48,          51,          45,          48,          54],
        [         84,          49,          51,          58,          52],
        [         49,          58,          49,          52,          46]],
       dtype=torch.int32)

In [ ]:
b

tensor([[2, 3],
        [4, 5]], dtype=torch.int32)

In [ ]:
y = a + z
y

tensor([[-1.6364e+09,  2.2069e+04,  5.0000e+01,  4.9000e+01,  4.5000e+01],
        [ 4.8000e+01,  5.1000e+01,  4.5000e+01,  4.8000e+01,  5.4000e+01],
        [ 8.4000e+01,  4.9000e+01,  5.1000e+01,  5.8000e+01,  5.2000e+01],
        [ 4.9000e+01,  5.8000e+01,  4.9000e+01,  5.2000e+01,  4.6000e+01]])

In [ ]:
y.dtype

torch.float32

In [ ]:
torch.add(z, a)

tensor([[-1.6364e+09,  2.2069e+04,  5.0000e+01,  4.9000e+01,  4.5000e+01],
        [ 4.8000e+01,  5.1000e+01,  4.5000e+01,  4.8000e+01,  5.4000e+01],
        [ 8.4000e+01,  4.9000e+01,  5.1000e+01,  5.8000e+01,  5.2000e+01],
        [ 4.9000e+01,  5.8000e+01,  4.9000e+01,  5.2000e+01,  4.6000e+01]])

In [ ]:
a = torch.rand(4,5) #0~1
a

tensor([[0.4623, 0.4433, 0.1644, 0.4840, 0.8334],
        [0.8323, 0.8297, 0.6471, 0.5632, 0.9902],
        [0.9689, 0.5688, 0.5299, 0.4546, 0.5367],
        [0.0705, 0.3011, 0.9628, 0.7412, 0.0831]])

In [ ]:
a.dtype

torch.float32

In [ ]:
b = a.numpy()
b

array([[0.46234262, 0.4433301 , 0.1644026 , 0.4840269 , 0.8333743 ],
       [0.83228546, 0.8296826 , 0.6471261 , 0.56316286, 0.99022496],
       [0.9688901 , 0.5688293 , 0.5299298 , 0.45463014, 0.5367443 ],
       [0.07054657, 0.30114675, 0.9627911 , 0.7411657 , 0.08309686]],
      dtype=float32)

In [ ]:
import numpy as np

In [ ]:
a = np.ones(5)
b = torch.from_numpy(a)#傳位置 a變b也變
a

array([1., 1., 1., 1., 1.])

In [ ]:
b#注意型態 是numpy轉乘tensor會是float64

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [ ]:
np.add(a, 1, out=a)

array([2., 2., 2., 2., 2.])

In [ ]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [ ]:
c = b + torch.FloatTensor([1,2,3,4,5])
c

tensor([3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
c = c.float()
c.dtype

torch.float32

In [ ]:
c = c.double()
c.dtype

torch.float64

In [ ]:
c = c.int()
c

tensor([3, 4, 5, 6, 7], dtype=torch.int32)

In [ ]:
x = torch.zeros(2,1,2,1,2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [ ]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [ ]:
y = torch.squeeze(x,0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = torch.squeeze(x,1)
y.size()

torch.Size([2, 2, 1, 2])

In [ ]:
y = torch.squeeze(y,2)
y.size()

torch.Size([2, 2, 2])

In [ ]:
torch.abs(torch.FloatTensor([-1,-2,3]))

tensor([1., 2., 3.])

In [ ]:
a = torch.randn(4)
a

tensor([-1.6528,  0.3647, -0.2370,  0.1542])

In [ ]:
b = torch.add(a, 20)
b

tensor([18.3472, 20.3647, 19.7630, 20.1542])

In [ ]:
c = torch.mul(a, 0.1)
c

tensor([-0.1653,  0.0365, -0.0237,  0.0154])

In [ ]:
d = torch.mul(a,b)#個元素相乘

In [ ]:
d

tensor([-30.3249,   7.4276,  -4.6848,   3.1081])

In [ ]:
x = torch.rand(2,3)
y = torch.rand(3,2)
x 

tensor([[0.1183, 0.5018, 0.4667],
        [0.7130, 0.4210, 0.2154]])

In [ ]:
y

tensor([[0.4754, 0.5050],
        [0.6195, 0.1833],
        [0.4659, 0.2542]])

In [ ]:
y.size()

torch.Size([3, 2])

In [ ]:
d = torch.matmul(y, x)#二維矩陣相乘 三維報錯 #跟dot差別
d

tensor([[0.4163, 0.4511, 0.3306],
        [0.2040, 0.3880, 0.3286],
        [0.2363, 0.3408, 0.2722]])

In [ ]:
print(y.mean())
k=y.mean()
print(k)
print(k.data)

tensor(0.4172)
tensor(0.4172)
tensor(0.4172)


In [ ]:
torch.mean(y)

tensor(0.4172)

In [ ]:
torch.mean(y,0)

tensor([0.5203, 0.3142])

In [ ]:
torch.mean(y,1)

tensor([0.4902, 0.4014, 0.3600])

In [ ]:
x = torch.Tensor([[1,2],[3,4]])
y = torch.Tensor([[1,1],[4,4]])

In [ ]:
x

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
y

tensor([[1., 1.],
        [4., 4.]])

In [ ]:
torch.eq(x,y)#形狀一樣才能比較

tensor([[ True, False],
        [False,  True]])

In [ ]:
torch.equal(x,y)

False

In [ ]:
torch.equal(y,y)

True

In [ ]:
torch.ge(x,y)#>=

tensor([[ True,  True],
        [False,  True]])

In [ ]:
torch.le(x,y)#<=

In [ ]:
torch.gt(x,y)#>

tensor([[False,  True],
        [False, False]])

In [ ]:
torch.lt(x,y)#<

tensor([[False, False],
        [ True, False]])